title = "Heartysoft Solutions Limited"
baseURL = "http://hsft.co/"
languageCode = "en"
theme = "hsft"
preserveTaxonomyNames = false
publishDir = "docs"

[permalinks]
"blog" = "/ashic/blog/:year/:month/:slug/"
